library(oro.nifti)
library(extrantsr)
library(fslr)
kirbydir <- "/home/fsluser/Desktop/MOOC-2015/kirby21"
mridir=file.path(kirbydir, 'visit_1','113')
T1_file=file.path(mridir,'113-01-MPRAGE.nii.gz')
T1=readNIfTI(T1_file,reorient=FALSE)
T2_file=file.path(mridir,'113-01-T2w.nii.gz')
T2w=readNIfTI(T2_file)
flirt_reg_t2_img = flirt(infile=T2_file,reffile=T1,dof=6,verbose=FALSE)
double_ortho(T1,flirt_reg_t2_img)
dim(T1)
dim(flirt_reg_t2_img)
dim(T2w)
