library(ANTsR)
aimg=antsImageRead('113-01-MPRAGE.nii.gz',dimension=3)
class(aimg)
mean(aimg)
mean(aimg[aimg!=0])
class(as.array(aimg))
library(devtools)
#devtools::install_github('muschellij2/extrantsr')
library(extrantsr)
class(nim <- ants2oro(aimg))